### ISSUE TITLE
HELLO I

### ISSUE THREAD

**Issue by lazyfighter** [IBM/janusgraph-utils#2]
![image](https://user-images.githubusercontent.com/17143488/28510011-69ae3a4a-7078-11e7-8706-eadd0e0ee26a.png)  i try to change my phoneIndex to disable ,but the index is always installed 
![image](https://user-images.githubusercontent.com/17143488/28510053-9aa9a3aa-7078-11e7-98fa-aca6ecbaed30.png)   help me please, how to remove the index -.-

**Comment by yhwang** [comment]
Hi @lazyfighter ,

Which version of janusgraph and what kind of storage backend you are using now?
In normal situation, when an new index is created, its state will transit from `INSTALLED` to `REGISTER`.  The transition happens when:
- The properties that are used by the newly created index are also created in the same transaction
- If the condition above is not qualified, there should be no other open transaction except the transaction that is used to create the new index

Be sure you can meet these 2 criteria when you create new index. Or the new index may stay in `INSTALLED`. Inside `updateCompositeIndexState`, I rollback other open transactions in order to prevent this situation. And in my latest code for the model/index creation, I also added the same trick.

Let me try to create your case. and see if I can find a way to remove it.

**Comment by yhwang** [comment]
Can you try:
`updateCompositeIndexState(graph, 'phoneIndex', SchemaAction.REMOVE_INDEX)`

**Comment by lazyfighter** [comment]
![image](https://user-images.githubusercontent.com/17143488/28607240-8b5653ee-720d-11e7-930c-ac25a0356d94.png)
i hava try this ,the index status is installed it cant remove

**Comment by lazyfighter** [comment]
I find problem , when  i must remove the hbase table and then restart gremlin-server ,and then try to build index ,first build the index ,it will turn to enable status ,but if i dont close the graph  just like janusGraph.close();  and then second try to build other index ,the index status will always be installed.


`
public class GraphTest {
    public static void main(String[] args) throws Exception {
        BaseConfiguration baseConfiguration = new BaseConfiguration();
        baseConfiguration.setProperty("storage.backend", "hbase");
        baseConfiguration.setProperty("storage.hostname", "192.168.1.108");
        baseConfiguration.setProperty("gremlin.graph", "org.janusgraph.core.JanusGraphFactory");
        JanusGraph janusGraph = JanusGraphFactory.open(baseConfiguration);
        GraphTraversalSource g = janusGraph.traversal();
        janusGraph.tx().rollback();
        JanusGraphManagement janusGraphManagement = janusGraph.openManagement();
        janusGraphManagement.makePropertyKey("name").dataType(String.class).cardinality(Cardinality.SINGLE).make();
        janusGraphManagement.commit();
        g.tx().commit();

        janusGraph.tx().rollback();
        janusGraphManagement = janusGraph.openManagement();
        janusGraphManagement.buildIndex("nameIndex", Vertex.class).addKey(janusGraphManagement.getPropertyKey("name")).unique().buildCompositeIndex();
        janusGraphManagement.commit();
        g.tx().commit();
        ManagementSystem.awaitGraphIndexStatus(janusGraph, "nameIndex")
                .status(SchemaStatus.REGISTERED)
                .timeout(5, ChronoUnit.MINUTES)
                .call();
        janusGraphManagement = janusGraph.openManagement();
        JanusGraphIndex imeiIndex = janusGraphManagement.getGraphIndex("nameIndex");
        janusGraphManagement.updateIndex(imeiIndex, SchemaAction.REINDEX);
        janusGraphManagement.commit();
        System.out.println("---------------------rebuldindexsucess...");
        janusGraph.tx().commit();

        janusGraphManagement = janusGraph.openManagement();
        imeiIndex = janusGraphManagement.getGraphIndex("nameIndex");
        janusGraphManagement.updateIndex(imeiIndex,SchemaAction.ENABLE_INDEX);
        janusGraphManagement.commit();
        janusGraph.tx().commit();
        janusGraph.close();
    }
}
`
if i dont use this code `janusGraph.close();`  the status cant be enable ,if i try to force stop my Application and dont normal stop Graph ， and then try to build index ,the index status will always be install
